version: '3'
services:
  airflow:
    user: root # Avoid permission problem when registering artifact
    build: .
    image: airflow-custom:latest
    container_name: airflow
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false" # Set true for having a list of examples to play
      AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.default"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./config:/opt/airflow/config
      - ./mlruns:/mlflow/artifacts  
    ports:
      - "8080:8080"
    command: >
      bash -c "
        airflow db migrate &&
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
        airflow variables import /opt/airflow/config/variables.json &&
        airflow webserver & airflow scheduler
      "
      
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
    volumes:
      - ./mlruns:/mlflow/artifacts
